# Generated by Django 5.1.5 on 2026-03-21 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Pipeline Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='Default Pipeline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'db_table': 'pipelines',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order')),
                ('probability', models.IntegerField(default=0, help_text='Likelihood of closing deals in this stage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Win Probability (%)')),
                ('color', models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #6366f1)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='pipelines.pipeline', verbose_name='Pipeline')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'db_table': 'pipeline_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Deal Name')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deal Value')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('probability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Win Probability (%)')),
                ('expected_close_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expected Close Date')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('lost_reason', models.TextField(blank=True, verbose_name='Lost Reason')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='contacts.contact', verbose_name='Contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='pipelines.pipelinestage', verbose_name='Pipeline Stage')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('NOTE', 'Note'), ('TASK', 'Task')], db_index=True, max_length=20, verbose_name='Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact', verbose_name='Contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='pipelines.deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'db_table': 'interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', '-created_at'], name='interaction_contact_7a6665_idx'), models.Index(fields=['deal', '-created_at'], name='interaction_deal_id_bb68e8_idx'), models.Index(fields=['agent', 'scheduled_at'], name='interaction_agent_i_a3fead_idx'), models.Index(fields=['interaction_type', 'scheduled_at'], name='interaction_interac_146f60_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['pipeline', 'order'], name='pipeline_st_pipelin_43e393_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('pipeline', 'order')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', 'stage'], name='deals_status_eea9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'status'], name='deals_owner_i_82e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date'], name='deals_expecte_53925b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['contact', 'status'], name='deals_contact_774593_idx'),
        ),
    ]
