# Generated by Django 5.1.5 on 2026-03-21 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Template Name')),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20, verbose_name='Channel Type')),
                ('subject', models.CharField(blank=True, help_text='For email templates only', max_length=500, verbose_name='Subject')),
                ('content', models.TextField(help_text='Template content with variable placeholders (e.g., {{first_name}})', verbose_name='Content')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names used in the template', verbose_name='Variables')),
                ('version', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Version')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['channel_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Campaign Name')),
                ('campaign_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=20, verbose_name='Campaign Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('total_recipients', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Recipients')),
                ('sent_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sent Count')),
                ('open_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Open Count')),
                ('click_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Click Count')),
                ('bounce_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bounce Count')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.channel', verbose_name='Channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('segments', models.ManyToManyField(blank=True, related_name='campaigns', to='contacts.contactgroup', verbose_name='Target Segments')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['channel_type', 'is_active'], name='templates_channel_fd1dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['name'], name='templates_name_061fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaigns_status_fe06f1_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_type', 'status'], name='campaigns_campaig_93ffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-created_at'], name='campaigns_created_163163_idx'),
        ),
    ]
