# Generated by Django 5.1.5 on 2026-03-21 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tag Name')),
                ('color', models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #6366f1)', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color')),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Company Name')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Domain')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Industry')),
                ('size', models.CharField(blank=True, choices=[('MICRO', 'Micro (1-10)'), ('SMALL', 'Small (11-50)'), ('MEDIUM', 'Medium (51-200)'), ('LARGE', 'Large (201-1000)'), ('ENTERPRISE', 'Enterprise (1000+)')], max_length=20, verbose_name='Company Size')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNSUBSCRIBED', 'Unsubscribed')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('IMPORT', 'Import'), ('API', 'API'), ('FORM', 'Web Form')], db_index=True, default='MANUAL', max_length=20, verbose_name='Source')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.company', verbose_name='Company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_dynamic', models.BooleanField(default=False, verbose_name='Dynamic Group')),
                ('filter_criteria', models.JSONField(blank=True, default=dict, verbose_name='Filter Criteria')),
                ('contacts', models.ManyToManyField(blank=True, related_name='groups', to='contacts.contact', verbose_name='Contacts')),
            ],
            options={
                'verbose_name': 'Contact Group',
                'verbose_name_plural': 'Contact Groups',
                'db_table': 'contact_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Field Name')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('DROPDOWN', 'Dropdown'), ('BOOLEAN', 'Boolean')], max_length=20, verbose_name='Field Type')),
                ('entity_type', models.CharField(choices=[('CONTACT', 'Contact'), ('COMPANY', 'Company'), ('DEAL', 'Deal')], db_index=True, max_length=20, verbose_name='Entity Type')),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdown fields, list of available options', verbose_name='Options')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Custom Field Definition',
                'verbose_name_plural': 'Custom Field Definitions',
                'db_table': 'custom_field_definitions',
                'ordering': ['entity_type', 'order', 'name'],
                'indexes': [models.Index(fields=['entity_type', 'order'], name='custom_fiel_entity__1e99cf_idx')],
                'unique_together': {('entity_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('pinned', models.BooleanField(db_index=True, default=False, verbose_name='Pinned')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'contact_notes',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='companies_domain_60b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['industry', 'size'], name='companies_industr_951cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['contact', '-pinned', '-created_at'], name='contact_not_contact_c99f43_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_email_2eb381_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', 'created_at'], name='contacts_status_241cac_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'status'], name='contacts_company_7f17eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'status'], name='contacts_owner_i_65367d_idx'),
        ),
    ]
