# Generated by Django 5.1.5 on 2026-03-21 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Automation Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('trigger_type', models.CharField(choices=[('CONTACT_CREATED', 'Contact Created'), ('TAG_ADDED', 'Tag Added'), ('STAGE_CHANGED', 'Stage Changed'), ('DEAL_CREATED', 'Deal Created'), ('FORM_SUBMITTED', 'Form Submitted')], db_index=True, max_length=50, verbose_name='Trigger Type')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='List of conditions that must be met for automation to run', verbose_name='Conditions')),
                ('actions', models.JSONField(blank=True, default=list, help_text='List of actions to execute when conditions are met', verbose_name='Actions')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Active')),
                ('execution_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Execution Count')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Executed At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'db_table': 'automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_data', models.JSONField(blank=True, default=dict, verbose_name='Trigger Data')),
                ('actions_executed', models.JSONField(blank=True, default=list, verbose_name='Actions Executed')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], db_index=True, max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('execution_time_ms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Execution Time (ms)')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation', verbose_name='Automation')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'db_table': 'automation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Webhook Name')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Webhook URL')),
                ('events', models.JSONField(blank=True, default=list, help_text='List of event types this webhook subscribes to', verbose_name='Events')),
                ('secret', models.CharField(blank=True, help_text='Secret key for signing webhook payloads', max_length=200, verbose_name='Secret Key')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered At')),
                ('failure_count', models.IntegerField(default=0, help_text='Consecutive failures - webhook disabled after threshold', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Failure Count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=100, verbose_name='Event')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='Response Status Code')),
                ('response_body', models.TextField(blank=True, verbose_name='Response Body')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Success')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Attempted At')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='automations.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'db_table': 'webhook_deliveries',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automations_trigger_45de4f_idx'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['is_active', 'last_executed_at'], name='automations_is_acti_bedacb_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['automation', '-created_at'], name='automation__automat_1669c5_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlog',
            index=models.Index(fields=['status', '-created_at'], name='automation__status_76428b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['is_active', 'last_triggered_at'], name='webhooks_is_acti_c8a5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-attempted_at'], name='webhook_del_webhook_227421_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event', '-attempted_at'], name='webhook_del_event_8e9b58_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['success', '-attempted_at'], name='webhook_del_success_9f1811_idx'),
        ),
    ]
