# Generated by Django 5.1.5 on 2026-03-21 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Channel Name')),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('CHAT', 'Chat')], db_index=True, max_length=20, verbose_name='Channel Type')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Channel-specific configuration (e.g., SMTP settings, API endpoints)', verbose_name='Configuration')),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='API keys, tokens, passwords (should be encrypted in production)', verbose_name='Credentials')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_channels', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'db_table': 'channels',
                'ordering': ['channel_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, default='OUTBOUND', max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('room', models.CharField(db_index=True, max_length=100, verbose_name='Chat Room')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_messages', to='communications.channel', verbose_name='Channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='contacts.contact', verbose_name='Contact')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_%(class)s_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, default='OUTBOUND', max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(max_length=500, verbose_name='Subject')),
                ('body_html', models.TextField(verbose_name='HTML Body')),
                ('body_text', models.TextField(blank=True, verbose_name='Plain Text Body')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment metadata', verbose_name='Attachments')),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Tracking ID')),
                ('opened', models.BooleanField(db_index=True, default=False, verbose_name='Opened')),
                ('open_count', models.IntegerField(default=0, verbose_name='Open Count')),
                ('first_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='First Opened At')),
                ('clicked', models.BooleanField(db_index=True, default=False, verbose_name='Clicked')),
                ('click_count', models.IntegerField(default=0, verbose_name='Click Count')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_messages', to='communications.channel', verbose_name='Channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='contacts.contact', verbose_name='Contact')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_%(class)s_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'email_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, default='OUTBOUND', max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('body', models.TextField(help_text='Maximum 1600 characters (10 segments)', max_length=1600, verbose_name='Message Body')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provider Message ID')),
                ('provider_status', models.CharField(blank=True, max_length=50, verbose_name='Provider Status')),
                ('segments', models.IntegerField(default=1, verbose_name='Message Segments')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_messages', to='communications.channel', verbose_name='Channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='contacts.contact', verbose_name='Contact')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_%(class)s_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'db_table': 'sms_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, default='OUTBOUND', max_length=20, verbose_name='Direction')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('body', models.TextField(blank=True, verbose_name='Message Body')),
                ('media_type', models.CharField(choices=[('NONE', 'None'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio')], default='NONE', max_length=20, verbose_name='Media Type')),
                ('media_url', models.URLField(blank=True, verbose_name='Media URL')),
                ('template_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Template Name')),
                ('template_params', models.JSONField(blank=True, default=dict, verbose_name='Template Parameters')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_messages', to='communications.channel', verbose_name='Channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_messages', to='contacts.contact', verbose_name='Contact')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_%(class)s_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type', 'is_active'], name='channels_channel_b102bb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chat_messag_room_cb84be_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'read'], name='chat_messag_room_1feb78_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['contact', 'status'], name='chat_messag_contact_ca7666_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'created_at'], name='email_messa_status_50c6df_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['tracking_id'], name='email_messa_trackin_a0e120_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['opened', 'created_at'], name='email_messa_opened_14e94b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['contact', 'status'], name='email_messa_contact_7c3b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['status', 'created_at'], name='sms_message_status_058598_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['provider_message_id'], name='sms_message_provide_11b553_idx'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['contact', 'status'], name='sms_message_contact_77b496_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['status', 'created_at'], name='whatsapp_me_status_66bcab_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['template_name'], name='whatsapp_me_templat_b045f2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['contact', 'status'], name='whatsapp_me_contact_ad47fc_idx'),
        ),
    ]
